package pool

//type Order struct {
//	Account               int64            `json:"account"`
//	AvgPx                 optional.Float64 `json:"avgPx"`
//	ClOrdID               optional.String  `json:"clOrdID"`
//	ClOrdLinkID           optional.String  `json:"clOrdLinkID"`
//	ContingencyType       optional.String  `json:"contingencyType"`
//	CumQty                optional.Float64 `json:"cumQty"`
//	Currency              optional.String  `json:"currency"`
//	DisplayQty            optional.Float64 `json:"displayQty"`
//	ExDestination         optional.String  `json:"exDestination"`
//	ExecInst              optional.String  `json:"execInst"`
//	LeavesQty             optional.Float64 `json:"leavesQty"`
//	MultiLegReportingType optional.String  `json:"multiLegReportingType"`
//	OrdRejReason          optional.String  `json:"ordRejReason"`
//	OrdStatus             optional.String  `json:"ordStatus"`
//	OrdType               optional.String  `json:"ordType"`
//	OrderID               string           `json:"orderID"`
//	OrderQty              optional.Float64 `json:"orderQty"`
//	PegOffsetValue        optional.Float64 `json:"pegOffsetValue"`
//	PegPriceType          optional.String  `json:"pegPriceType"`
//	Price                 optional.Float64 `json:"price"`
//	SettlCurrency         optional.String  `json:"settlCurrency"`
//	Side                  optional.String  `json:"side"`
//	SimpleCumQty          optional.Float64 `json:"simpleCumQty"`
//	SimpleLeavesQty       optional.Float64 `json:"simpleLeavesQty"`
//	SimpleOrderQty        optional.Float64 `json:"simpleOrderQty"`
//	StopPx                optional.Float64 `json:"stopPx"`
//	Symbol                optional.String  `json:"symbol"`
//	Text                  optional.String  `json:"text"`
//	TimeInForce           optional.String  `json:"timeInForce"`
//	Timestamp             time.Time        `json:"timestamp"`
//	TransactTime          time.Time        `json:"transactTime"`
//	Triggered             optional.String  `json:"triggered"`
//	WorkingIndicator      optional.Bool    `json:"workingIndicator"`
//}
//
//type Position struct {
//	Account              int64            `json:"account"`
//	AvgCostPrice         optional.Float64 `json:"avgCostPrice"`
//	AvgEntryPrice        optional.Float64 `json:"avgEntryPrice"`
//	BankruptPrice        optional.Float64 `json:"bankruptPrice"`
//	BreakEvenPrice       optional.Float64 `json:"breakEvenPrice"`
//	Commission           optional.Float64 `json:"commission"`
//	CrossMargin          optional.Bool    `json:"crossMargin"`
//	Currency             optional.String  `json:"currency"`
//	CurrentComm          optional.Float64 `json:"currentComm"`
//	CurrentCost          optional.Float64 `json:"currentCost"`
//	CurrentQty           optional.Float64 `json:"currentQty"`
//	CurrentTimestamp     optional.Time    `json:"currentTimestamp"`
//	DeleveragePercentile optional.Float64 `json:"deleveragePercentile"`
//	ExecBuyCost          optional.Float64 `json:"execBuyCost"`
//	ExecBuyQty           optional.Float64 `json:"execBuyQty"`
//	ExecComm             optional.Float64 `json:"execComm"`
//	ExecCost             optional.Float64 `json:"execCost"`
//	ExecQty              optional.Float64 `json:"execQty"`
//	ExecSellCost         optional.Float64 `json:"execSellCost"`
//	ExecSellQty          optional.Float64 `json:"execSellQty"`
//	ForeignNotional      optional.Float64 `json:"foreignNotional"`
//	GrossExecCost        optional.Float64 `json:"grossExecCost"`
//	GrossOpenCost        optional.Float64 `json:"grossOpenCost"`
//	GrossOpenPremium     optional.Float64 `json:"grossOpenPremium"`
//	HomeNotional         optional.Float64 `json:"homeNotional"`
//	IndicativeTax        optional.Float64 `json:"indicativeTax"`
//	IndicativeTaxRate    optional.Float64 `json:"indicativeTaxRate"`
//	InitMargin           optional.Float64 `json:"initMargin"`
//	InitMarginReq        optional.Float64 `json:"initMarginReq"`
//	IsOpen               optional.Bool    `json:"isOpen"`
//	LastPrice            optional.Float64 `json:"lastPrice"`
//	LastValue            optional.Float64 `json:"lastValue"`
//	Leverage             optional.Float64 `json:"leverage"`
//	LiquidationPrice     optional.Float64 `json:"liquidationPrice"`
//	LongBankrupt         optional.Float64 `json:"longBankrupt"`
//	MaintMargin          optional.Float64 `json:"maintMargin"`
//	MaintMarginReq       optional.Float64 `json:"maintMarginReq"`
//	MarginCallPrice      optional.Float64 `json:"marginCallPrice"`
//	MarkPrice            optional.Float64 `json:"markPrice"`
//	MarkValue            optional.Float64 `json:"markValue"`
//	OpenOrderBuyCost     optional.Float64 `json:"openOrderBuyCost"`
//	OpenOrderBuyPremium  optional.Float64 `json:"openOrderBuyPremium"`
//	OpenOrderBuyQty      optional.Float64 `json:"openOrderBuyQty"`
//	OpenOrderSellCost    optional.Float64 `json:"openOrderSellCost"`
//	OpenOrderSellPremium optional.Float64 `json:"openOrderSellPremium"`
//	OpenOrderSellQty     optional.Float64 `json:"openOrderSellQty"`
//	OpeningComm          optional.Float64 `json:"openingComm"`
//	OpeningCost          optional.Float64 `json:"openingCost"`
//	OpeningQty           optional.Float64 `json:"openingQty"`
//	OpeningTimestamp     optional.Time    `json:"openingTimestamp"`
//	PosAllowance         optional.Float64 `json:"posAllowance"`
//	PosComm              optional.Float64 `json:"posComm"`
//	PosCost              optional.Float64 `json:"posCost"`
//	PosCost2             optional.Float64 `json:"posCost2"`
//	PosCross             optional.Float64 `json:"posCross"`
//	PosInit              optional.Float64 `json:"posInit"`
//	PosLoss              optional.Float64 `json:"posLoss"`
//	PosMaint             optional.Float64 `json:"posMaint"`
//	PosMargin            optional.Float64 `json:"posMargin"`
//	PosState             optional.String  `json:"posState"`
//	PrevClosePrice       optional.Float64 `json:"prevClosePrice"`
//	PrevRealisedPnl      optional.Float64 `json:"prevRealisedPnl"`
//	PrevUnrealisedPnl    optional.Float64 `json:"prevUnrealisedPnl"`
//	QuoteCurrency        optional.String  `json:"quoteCurrency"`
//	RealisedCost         optional.Float64 `json:"realisedCost"`
//	RealisedGrossPnl     optional.Float64 `json:"realisedGrossPnl"`
//	RealisedPnl          optional.Float64 `json:"realisedPnl"`
//	RealisedTax          optional.Float64 `json:"realisedTax"`
//	RebalancedPnl        optional.Float64 `json:"rebalancedPnl"`
//	RiskLimit            optional.Float64 `json:"riskLimit"`
//	RiskValue            optional.Float64 `json:"riskValue"`
//	SessionMargin        optional.Float64 `json:"sessionMargin"`
//	ShortBankrupt        optional.Float64 `json:"shortBankrupt"`
//	SimpleCost           optional.Float64 `json:"simpleCost"`
//	SimplePnl            optional.Float64 `json:"simplePnl"`
//	SimplePnlPcnt        optional.Float64 `json:"simplePnlPcnt"`
//	SimpleQty            optional.Float64 `json:"simpleQty"`
//	SimpleValue          optional.Float64 `json:"simpleValue"`
//	Symbol               string           `json:"symbol"`
//	TargetExcessMargin   optional.Float64 `json:"targetExcessMargin"`
//	TaxBase              optional.Float64 `json:"taxBase"`
//	TaxableMargin        optional.Float64 `json:"taxableMargin"`
//	Timestamp            optional.Time    `json:"timestamp"`
//	Underlying           optional.String  `json:"underlying"`
//	UnrealisedCost       optional.Float64 `json:"unrealisedCost"`
//	UnrealisedGrossPnl   optional.Float64 `json:"unrealisedGrossPnl"`
//	UnrealisedPnl        optional.Float64 `json:"unrealisedPnl"`
//	UnrealisedPnlPcnt    optional.Float64 `json:"unrealisedPnlPcnt"`
//	UnrealisedRoePcnt    optional.Float64 `json:"unrealisedRoePcnt"`
//	UnrealisedTax        optional.Float64 `json:"unrealisedTax"`
//	VarMargin            optional.Float64 `json:"varMargin"`
//}
//
//type Margin struct {
//	Account            int64            `json:"account"`
//	Action             optional.String  `json:"action"`
//	Amount             optional.Float64 `json:"amount"`
//	AvailableMargin    optional.Float64 `json:"availableMargin"`
//	Commission         optional.Float64 `json:"commission"`
//	ConfirmedDebit     optional.Float64 `json:"confirmedDebit"`
//	Currency           string           `json:"currency"`
//	ExcessMargin       optional.Float64 `json:"excessMargin"`
//	ExcessMarginPcnt   optional.Float64 `json:"excessMarginPcnt"`
//	GrossComm          optional.Float64 `json:"grossComm"`
//	GrossExecCost      optional.Float64 `json:"grossExecCost"`
//	GrossLastValue     optional.Float64 `json:"grossLastValue"`
//	GrossMarkValue     optional.Float64 `json:"grossMarkValue"`
//	GrossOpenCost      optional.Float64 `json:"grossOpenCost"`
//	GrossOpenPremium   optional.Float64 `json:"grossOpenPremium"`
//	IndicativeTax      optional.Float64 `json:"indicativeTax"`
//	InitMargin         optional.Float64 `json:"initMargin"`
//	MaintMargin        optional.Float64 `json:"maintMargin"`
//	MakerFeeDiscount   optional.Float64 `json:"makerFeeDiscount"`
//	MarginBalance      optional.Float64 `json:"marginBalance"`
//	MarginBalancePcnt  optional.Float64 `json:"marginBalancePcnt"`
//	MarginLeverage     optional.Float64 `json:"marginLeverage"`
//	MarginUsedPcnt     optional.Float64 `json:"marginUsedPcnt"`
//	PendingCredit      optional.Float64 `json:"pendingCredit"`
//	PendingDebit       optional.Float64 `json:"pendingDebit"`
//	PrevRealisedPnl    optional.Float64 `json:"prevRealisedPnl"`
//	PrevState          optional.String  `json:"prevState"`
//	PrevUnrealisedPnl  optional.Float64 `json:"prevUnrealisedPnl"`
//	RealisedPnl        optional.Float64 `json:"realisedPnl"`
//	RiskLimit          optional.Float64 `json:"riskLimit"`
//	RiskValue          optional.Float64 `json:"riskValue"`
//	SessionMargin      optional.Float64 `json:"sessionMargin"`
//	State              optional.String  `json:"state"`
//	SyntheticMargin    optional.Float64 `json:"syntheticMargin"`
//	TakerFeeDiscount   optional.Float64 `json:"takerFeeDiscount"`
//	TargetExcessMargin optional.Float64 `json:"targetExcessMargin"`
//	TaxableMargin      optional.Float64 `json:"taxableMargin"`
//	Timestamp          optional.Time    `json:"timestamp"`
//	UnrealisedPnl      optional.Float64 `json:"unrealisedPnl"`
//	UnrealisedProfit   optional.Float64 `json:"unrealisedProfit"`
//	VarMargin          optional.Float64 `json:"varMargin"`
//	WalletBalance      optional.Float64 `json:"walletBalance"`
//	WithdrawableMargin optional.Float64 `json:"withdrawableMargin"`
//}
